name: Playwright Tests

on:
  push:
    branches: [main, login-basic-clean]
  pull_request:
    branches: [main, login-basic-clean]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
